import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.js', 'public/js/*.js', 'public/admin/*.js'],
    ignores: ['node_modules/**', 'uploads/**'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        io: 'writable',
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        Notification: 'readonly',
        location: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        requestAnimationFrame: 'readonly',
        atob: 'readonly',
        Uint8Array: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        self: 'readonly',
        clients: 'readonly',
        caches: 'readonly',
        addEventListener: 'readonly',
        btoa: 'readonly',
        Headers: 'readonly',
        Blob: 'readonly',
      },
    },
    rules: {
      semi: ['warn', 'always'],
      quotes: ['warn', 'single', { avoidEscape: true }],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-undef': 'off',
      'no-empty': 'warn',
      'no-extra-semi': 'warn',
      'no-multi-spaces': 'warn',
      'no-trailing-spaces': 'warn',
      'comma-dangle': ['warn', 'never'],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-prototype-builtins': 'off',
      'no-useless-catch': 'off',
      'no-constant-condition': ['warn', { checkLoops: false }],
      'no-unused-expressions': 'off',
    },
  },
  {
    files: ['public/js/*.js', 'public/admin/*.js'],
    languageOptions: {
      sourceType: 'script',
    },
  },
];
